services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: real_estate_crm_api

    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      mysql:
        condition: service_healthy

    command: npm run dev


  mysql:
    image: mysql:8.4

    container_name: real_estate_crm_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${DB_USER}",
          "-p${DB_PASSWORD}"
        ]

      interval: 5s
      timeout: 5s
      retries: 20


volumes:
  mysql_data: